<template>
  <div id="compo-api-composables-main">
    <h2>Options API</h2>
    <p>This is an example of the Options API. We just parse in a <code>message</code> variable from the data property in our component.</p>
    <p>{{ message }}</p>
    <h2>Composition API</h2>
    <p>We brought this in from the Composition API! The width is a value generated by a function that lies in <code>src/composables/&lt;functionName&gt;.ts</code>. That's how we can easily display the window width <router-link to="/home/#width">right over here</router-link>, too</p>
    <p>{{ width }}</p>
    <button @click="reportWidth">Show Width in Alert Box</button>
    <p>{{ widthDoubled }}</p>
  </div>
</template>

<script setup lang="ts">
import useWindowWidth from "../composables/useWindowWidth";
import {computed} from "vue";

const message = "Hi from Options API!"
const width = useWindowWidth();
const widthDoubled = computed (() => {
  console.log(width)

  return width.value * 2;
});
const reportWidth = () => {
      alert(width);
};
</script>

<style>
#compo-api-composables-main {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
